# Generated by Django 6.0.7 on 2026-07-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('aberto', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.funcionario')),
            ],
        ),
    ]
