# Generated by Django 6.0.7 on 2026-07-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='registers.funcionario'),
        ),
    ]
