# Generated by Django 6.0.7 on 2026-07-08 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senha', models.CharField(help_text='Senha numérica de 4 dígitos', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='A senha deve conter exatamente 4 dígitos numéricos.', regex='^\\d{4}$')])),
            ],
        ),
    ]
